resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: project-source
  type: pull-request
  check_every: 24h
  webhook_token: ((webhook-token))
  source:
    repository: CardinalHealth/rdw-application
    access_token: ((access-token))

- name: ci
  type: git
  source:
    uri: 'https://github.com/cah-omar-yusuf/ci.git'
    branch: configure-gradle-test
    private_key: ((rdw.RDW_APPLICATION_GIT_PK))

jobs:
  - name: Unit Test
    max_in_flight: 1
    plan:
      - get: ci
      - get: project-source
        trigger: true
        version: every
      - put: project-source
        params:
          base_context: check
          context: unit-test
          path: project-source
          status: pending
      - task: gradle-test
        file: ci/tasks/gradle-test.yml
        params:
          RDW_AUTH_URL: https://identity.dev.cardinalhealth.net/oauth2/v1/introspect
          RDW_CLIENTID: 0oap5xgcnhBEQtjom0h7
          RDW_POSTGRES_URL: jdbc:postgresql://rdwpostgresdev01.Cardinalhealth.net/rdw
          RDW_POSTGRES_USERID: postgres
          RDW_RESOURCE_ID: https://identity.dev.cardinalhealth.net
          RDW_USERINFO_URL: https://identity.dev.cardinalhealth.net/oauth2/v1/userinfo
          RDW_PROJECT_ID: pharmaqra-np-cah
          GOOGLE_APPLICATION_CREDENTIALS_BASE64: ((rdw.GOOGLE_APPLICATION_CREDENTIALS_BASE64_NP))
          CURRENT_ENV: dev
          APP_NAME: RDW
        on_success:
          put: project-source
          params:
            base_context: check
            context: unit-test
            path: project-source
            status: success
        on_failure:
          put: project-source
          params:
            base_context: check
            context: unit-test
            path: project-source
            status: failure