platform: linux

image_resource:
  type: registry-image
  source:
    repository: "nexus.cardinalhealth.net:8445/openjdk"
    tag: 11.0-jre-slim
inputs:
  - name: project-source
  - name: ci
run:
  path: /bin/sh
  args: ["ci/scripts/gradle-test.sh"]
caches:
  - path: .gradle/

params:
  TERM: -dumb
