platform: linux

image_resource:
  type: registry-image
  source:
    repository: "nexus-nonprod.cardinalhealth.net:8445/timbru31/java-node"
    tag: jdk
inputs:
  - name: project-source
  - name: ci
run:
  path: /bin/sh
  args: ["ci/scripts/gradle-build.sh"]
caches:
  - path: .gradle/
outputs:
  - name: project-source
params:
  TERM: -dumb
