platform: linux

image_resource:
  type: registry-image
  source:
    repository: "nexus-nonprod.cardinalhealth.net:8445/timbru31/java-node"
    tag: jdk
inputs:
  - name: project-source
  - name: ci
run:
  path: /bin/sh
  args: ["ci/scripts/gradle-build.sh"]
caches:
  - path: .gradle/
outputs:
  - name: project-source
params:
  RDW_AUTH_URL: https://identity.dev.cardinalhealth.net/oauth2/v1/introspect
  RDW_CLIENTID: 0oap5xgcnhBEQtjom0h7
  RDW_POSTGRES_URL: jdbc:postgresql://rdwpostgresdev01.Cardinalhealth.net/rdw
  RDW_POSTGRES_USERID: postgres
  RDW_RESOURCE_ID: https://identity.dev.cardinalhealth.net
  RDW_USERINFO_URL: https://identity.dev.cardinalhealth.net/oauth2/v1/userinfo
  RDW_PROJECT_ID: pharmaqra-np-cah
  GOOGLE_APPLICATION_CREDENTIALS_BASE64: ((rdw.GOOGLE_APPLICATION_CREDENTIALS_BASE64_NP))
  CURRENT_ENV: dev
  APP_NAME: RDW
  TERM: -dumb
